services:
  - type: web
    name: allytics
    env: python
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
    plan: free
